services:
  api:
    build: api
    container_name: "sudoku-api"

  front:
    build: front
    container_name: "sudoku-front"

  nginx:
    build: nginx
    container_name: "sudoku-nginx"
    ports:
      - "7854:80"